version: '3.8'

services:
  shell-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    working_dir: /workspace
  prettier:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["lint-prettier"]
    volumes:
      - .:/workspace
    working_dir: /workspace
